otu<-read.table("otu.txt",,header=TRUE,sep="\t",row.names=1)
otu<-t(otu)
a<-otu
ra<-a
ra[ra>0.0001]<-0
abd<-a
abd[abd<0.005]<-0
int<-a
int[int>0.005]<-0
int[int<0.0001]<-0
#######################################################################################
#########Taxonomic distribution of abundant and rare bacterial sub-communities#########
namec<-cbind(otuname,t(ra))
se_phy<-aggregate(namec[,8:45],by=list(namec$class),FUN=sum)
rownames(se_phy)<-se_phy[,1]
se_phy<-t(se_phy[,-1])
se_ra<-se_phy/rowSums(se_phy)
namec<-cbind(otuname,t(abd))
se_phy<-aggregate(namec[,8:45],by=list(namec$class),FUN=sum)
rownames(se_phy)<-se_phy[,1]
se_phy<-t(se_phy[,-1])
se_abd<-se_phy/rowSums(se_phy)
se<-rbind(se_abd,se_ra)
se<-se[,order(colSums(se),decreasing=T)]
se<-se[,c(-10,-14,-16,-22)]
se<-cbind(1-rowSums(se[,20:1]),se[,20:1])
fa<-rep(c("Abundant","Rare"),each=38)
seme<-aggregate(se,by=list(fa),FUN=mean)
sesd<-aggregate(se,by=list(fa),FUN=sd)
rownames(sesd)<-sesd[,1]
sesd<-as.matrix(sesd[,-1])*100
rownames(seme)<-seme[,1]
seme<-as.matrix(seme[,-1])*100
colnames(seme)[1]<-"Other classes"
dat<-se
for(i in 1:ncol(dat))
{
a<-wilcox.test(dat[,i]~fa,p.adj="BH",group=T)
b[i]<-fdrtool(a$p.value,statistic="pvalue")
}
pdf("class-1.pdf",height=8,width=10)
par(mar=c(5,12,2,2))
barplot2(seme,beside=TRUE,las=1,col=c("darkorange","cornflowerblue")
,border=NA,axes=F,horiz=T,xlim=c(0,40),ci.color = "gray20",
,cex.names=1.2,cex.lab=1.3,xlab="Proportion(%)",
plot.ci=T,ci.l=seme,ci.u=seme+sesd^0.5,ci.lwd=0.1)
axis(1,at=c(0,10,20,30,40),labels=c(0,10,20,30,40),cex.axis=1.3)
dev.off()
##########################################
##########alpha-diversity###########
a<-otu
ra<-a
ra[ra>0.0001]<-0
ra<-ra[,colSums(ra)>0]
abd<-a
abd[abd<0.005]<-0
abd<-abd[,colSums(abd)>0]
int<-a
int[int>0.005]<-0
int[int<0.0001]<-0
int<-int[,colSums(int)>0]
shra<-diversity(ra)
rira<-specnumber(ra)
enra<-shra/log(rira)
shint<-diversity(int)
riint<-specnumber(int)
enint<-shint/log(riint)
shabd<-diversity(abd)
riabd<-specnumber(abd)
enabd<-shabd/log(riabd)
shotu<-diversity(a)
riotu<-specnumber(a)
enotu<-shotu/log(riotu)
shcore<-diversity(core1)
ricore<-specnumber(core1)
encore<-shcore/log(ricore)
b1<-as.vector(c(shra,shint,shabd,shotu,shcore))
b2<-as.vector(c(rira,riint,riabd,riotu,ricore))
b3<-as.vector(c(enra,enint,enabd,enotu,encore))
b<-as.data.frame(cbind(shannon=b1,evenness=b3,richness=b2))
n<-nrow(a)
b$group<-c(rep("d",n),rep("c",n),rep("b",n),
rep("a",n),rep("e",n))
col<-c("darkgreen","darkorange","grey92","cornflowerblue","red2")
pdf("shannon.pdf",height=6,width=8)
par(mar=c(3,5,2,2))
boxplot(b$shannon~b$group,cex.axis=1.2,ylab="Shannon",cex.lab=1.5,
col=col,names=c("Whole","Abundant","Intermediate","Rare","Core"))
dev.off()
pdf("evenness.pdf",height=6,width=8)
par(mar=c(3,5,2,2))
boxplot(b$evenness~b$group,cex.axis=1.2,ylab="Evenness",cex.lab=1.5,
col=col,names=c("Whole","Abundant","Intermediate","Rare","Core"))
dev.off()
pdf("richness.pdf",height=6,width=8)
par(mar=c(3,5,2,2))
boxplot(b$richness~b$group,cex.axis=1.2,ylab="Richness",cex.lab=1.5,
col=col,names=c("Whole","Abundant","Intermediate","Rare","Core"))
dev.off()
